# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorial7akolar',
                'doc_host': 'https://AKolar5.github.io',
                'git_url': 'https://github.com/AKolar5/tutorial7akolar',
                'lib_path': 'tutorial7akolar'},
  'syms': {'tutorial7akolar.core': {'tutorial7akolar.core.foo': ('core.html#foo', 'tutorial7akolar/core.py')}}}